version: "3"
services:
  nginx:
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  node-app:
    build:
      context: .
      args:
        NODE_ENV: production
      environment:
        - NODE_ENV=production
        - MONGO_USER=dbadmin
        - MONGO_PASSWORD=dbpass
        - SESSION_SECRET=secret
    command: node index.js
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dbadmin
      - MONGO_INITDB_ROOT_PASSWORD=dbpass
