version: "3"
services:
  nginx:
    image: nginx:stable-alpine
  node-app:
    build: .
    environment:
      - PORT=3000
    depends_on:
      - mongo
  mongo:
    image: mongo
    # command: --serviceExecutor adaptive
    volumes:
      - mongo-db:/data/db
  redis:
    image: redis

volumes:
  mongo-db:
